name:         "Flake-Formatter Cache"
description:  "Cache a flake's formatter using cachix"
author:       "Maxine Zick"

runs:
  using: 'composite'
  steps:
    - shell:  bash
      run: |
        which cachix &> /dev/null || nix profile add --accept-flake-config nixpkgs#cachix

        if __item=$(nix formatter build --no-link 2> /dev/null); then
          cachix push flux-rs $(nix path-info --quiet ${__item} 2>/dev/null)
        fi

