name: "autofix.ci"

on:
  pull_request:
    branches:
      - staging

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: DeterminateSystems/determinate-nix-action@v3.21.0

      - name: "Nix Formatter"
        run: nix fmt --no-update-lock-file --accept-flake-config

      - uses: autofix-ci/action@v1
