name: "autofix.ci"

on:
  pull_request:
    branches:
      - staging

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ./.github/actions/determinate-nix-action

      - uses: ./.github/actions/cache-flake-formatter
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix Formatter"
        run: nix formatter run --no-update-lock-file --accept-flake-config

      - uses: autofix-ci/action@v1
