name: "Fixup Source"

on:
  pull_request:
    branches:
      - staging
  pull_request_target:
    branches:
      - staging

jobs:
  fixup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: DeterminateSystems/determinate-nix-action@v3.21.0

      - name: "Check Flake Outputs"
        run: nix flake check --no-update-lock-file --accept-flake-config .

      - name: "Nix Formatter"
        run: nix fmt --no-update-lock-file

      - uses: autofix-ci/action@v1
