name: "Validate Source"

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/determinate-nix-action

      - uses: ./.github/actions/cache-flake-formatter
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Nix Formatter: Run"
        run:  nix formatter run -- --ci

      - name: "Check Flake Outputs"
        run:  nix flake check --accept-flake-config --all-systems

